export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'


export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_INIT = "PURCHASE_INIT"


export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

export const SEARCH_HOTEL_START = 'SEARCH_HOTEL_START'
export const SEARCH_HOTEL_SUCCESS = 'SEARCH_HOTEL_SUCCESS'
export const SEARCH_HOTEL_FAIL = 'SEARCH_HOTEL_FAIL'

export const SEARCH_HOTELS_START = 'SEARCH_HOTEL_START'
export const SEARCH_HOTELS_SUCCESS = 'SEARCH_HOTEL_SUCCESS'
export const SEARCH_HOTELS_FAIL = 'SEARCH_HOTEL_FAIL'


export const USER_AUTH_START = "USER_AUTH_START"
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_FAIL = "USER_AUTH_FAIL"
export const USER_AUTH_LOGOUT = "USER_AUTH_LOGOUT"

export const OWNER_AUTH_START = "OWNER_AUTH_START"
export const OWNER_AUTH_SUCCESS = "OWNER_AUTH_SUCCESS"
export const OWNER_AUTH_FAIL = "OWNER_AUTH_FAIL"
export const OWNER_AUTH_LOGOUT = "OWNER_AUTH_LOGOUT"

export const SET_SEARCH_DETAILS_SUCCESS = "SET_SEARCH_DETAILS_SUCCESS"
export const SET_SEARCH_DETAILS_FAIL = "SET_SEARCH_DETAILS_FAIL"
export const SET_SEARCH_DETAILS_START = "SET_SEARCH_DETAILS_START"

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"

export const ADD_ROOMS = "ADD_ROOMS"
